# 01. 넘파이 배열의 생성
---
* 날짜:
* 이름:


Numpy(Numerical Python)는 고성능 과학 계산을 위한 파이썬 패키지로 강렬한 N차원의 배열(array)을 제공합니다. 이 배열은 범용적인 데이터 처리에 사용 가능한 다차원 컨테이너라 할 수 있으며 파이썬의 list와 비슷하지만 더 빠르고 효율적으로 메모리를 관리합니다. 배열에 대한 여러가지 연산 등 처리를 제공하며 데이터과학의 핵심이라 할 수 있습니다.

https://numpy.org/



```
import numpy as np
```



In [1]:
import numpy as np

## 개념정리
---



### **(1) 리스트 와 배열**

![](https://docs.sangyunlee.com/~/files/v0/b/gitbook-28427.appspot.com/o/assets%2F-LxaqUhwPNPE0iJCKfjJ%2F-MUgfOmYMQC2EJUN2rq_%2F-MUgttBGp-6BNnfXwC4R%2Fimage.png?alt=media&token=e3d4ca35-8fc8-473b-833a-f61ee70ab527)





* 리스트 생성

In [10]:
a1 = [ 2,5,6,9 ]

a2 = [ [3.5, 4.0, 6.5],
       [0.4, 0.9, 4.7] ]




# (2,3)
b1 = [ [ 1,1,1 ] , [1 ,1 ,1 ] ]
b1 = np.array(b1)
# (2,3,1)
b2 = [ [ [1], [1], [1] ] , [[1], [1], [1] ] ]
b2 = np.array(b2)
# (3,2)
b3 = [ [1,1],[1,1],[1,1] ] 
b3 = np.array(b3)
print(b1.shape, b2.shape, b3.shape)

# (2, 4, 3)
c1 = [ [ [7,9,2],
         [4,0,8],
         [1,3,6],
         [5,8,4] ],      
       [ [1,4,3],
         [0,0,0],
         [0,0,9],
         [0,0,7] ] ]
c1 = np.array(c1)

# (4, 3, 2)
c2 = [ [ [7,1], 
         [9,4], 
         [2,3] ], 
       [ [4,0], 
         [8,0], 
         [0,0] ], 
       [ [1,0], 
         [3,0], 
         [6,9] ], 
       [ [5,0], 
         [8,0], 
         [4,7] ] ]
c2 = np.array(c2)

# (3,2,4)
c3 = [ [[2,8,6,4], 
        [3,0,9,7] ], 
       [[9,0,3,8], 
        [4,0,0,0] ],
       [[7,4,1,5],
        [1,0,0,0] ]]
c3 = np.array(c3)

print(c1.shape, c2.shape, c3.shape)

(2, 3) (2, 3, 1) (3, 2)
(2, 4, 3) (4, 3, 2) (3, 2, 4)


* 리스트를 넘파이 어레이로 변환

In [3]:
a1 = np.array(a1)
a2 = np.array(a2)
a3 = np.array(a3)

* `.shape`: 배열의 shape 확인

In [5]:
a1.shape, a2.shape, a3.shape

((4,), (2, 3), (2, 4, 3))

### **(2) 배열 초기화**




#### **1. `zeros()`**

배열의 모든 요소를 0으로 초기화 합니다.


```
배열 = np.zeros(shape)
```



In [14]:
shape=(2,3)
a = np.zeros(shape)
a, a.shape

(array([[0., 0., 0.],
        [0., 0., 0.]]), (2, 3))

#### **2. `ones()`**

배열의 모든 요소를 1 로 초기화 합니다.
```
배열 = np.ones(shape)
```

In [15]:
a = np.ones(shape)
a, a.shape

(array([[1., 1., 1.],
        [1., 1., 1.]]), (2, 3))

#### **3. `full()`**

배열의 모든 요소를 지정 값으로 초기화 합니다.
```
배열 = np.full(shape, 지정값)
```

In [16]:
a = np.full(shape, 2)
a, a.shape

(array([[2, 2, 2],
        [2, 2, 2]]), (2, 3))

### **(3) 배열 생성**




#### **1. `eye()`**

단위행렬 (identity matrix)를 생성합니다. 단위 행렬이란 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬입니다.



```
배열 = np.eye(정수)
```



In [17]:
a = np.eye(3)
a, a.shape

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]), (3, 3))

#### **2. `empty()`**

초기화되지 않은 배열을 생성합니다. 초기화 되지 않은 배열은 생성이 빠릅니다.

```
배열 = np.empty(shape)
```

In [25]:
a  = np.empty(shape)
a, a.shape

(array([[1., 1., 1.],
        [1., 1., 1.]]), (2, 3))

#### **3. `_like()`**

특정 배열과 같은 shape가 같은 행렬을 생성합니다.

  * `np.zeros_like()`
  * `np.ones_like()`
  * `np.full_like()`
  * `np.empty_like()`

```
배열2  = np.()_like(배열1)
```


In [28]:
b = np.full_like(a,3)
b, b.shape

(array([[3., 3., 3.],
        [3., 3., 3.]]), (2, 3))

### **(3) 생성한 값으로 배열 생성**




#### **1. `arange()`**

정수 범위의 배열을 생성합니다.

```
배열 = np.arange(start, end, step)
```


In [31]:
a = np.arange(1, 11, 2)
a, a.shape

(array([1, 3, 5, 7, 9]), (5,))

#### **2. `linspace()`**

범위 내 균등 간격을 가지는 배열을 생성합니다.

```
배열  = np.linspace(start, end, bins)
```


In [38]:
a = np.linspace(1, 10, 20)
a, a.shape

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 (20,))

#### **3. `logspace()`**

범위 내 균등 간격을 가지는 로그 스케일의 배열을 생성합니다.

```
배열2  = np.logspace(start, end, bins)
```


In [44]:
a = np.logspace(1, 64, 4)
a, a.shape

(array([1.e+01, 1.e+22, 1.e+43, 1.e+64]), (4,))

### **(4) 랜덤값의 배열 생성**

| 함수 | 설명 |
|--|--|
| `seed` | 난수 발생을 위한 시드 지정|
| `permutation` | 순서 임의 변환, 임의의 순열 반환|
| `shuffle` | 리스트 또는 배열의 순서 섞기 |
| `random` | 랜덤값의 배열 생성|
| `rand` | 균등분포를 따르는 표본 추출|
| `randint` | 주어진 최소/최대 번위의 난수 추출 |
| `randn` | 표준정규분포를 따르는 표본 추출 |
| `binomial` | 이항분포를 따르는 표본 추출 |
| `normal` | 가우시안정규분포를 따르는 표본 추출 |
| `beta` | 베타분포를 따르는 표본 추출 |
| `chisquare` | 카이제곱분포를 따르는 표본 추출 |
| `gamma` | 감마분포를 따르는 표본 추출 |
| `uniform` | 균등분포를 따르는 표본 추출 |



#### **1. `rnadom.random()`**

랜덤 값을 지니는 배열을 생성합니다.



```
배열 = np.random.random(shape)
```



In [69]:
a = np.random.random(shape)
a, a.shape

(array([[0.95893643, 0.98988206, 0.16708245],
        [0.50338531, 0.50569276, 0.09464807]]), (2, 3))

#### **2. `random.randint()`**

일정 범위의 랜덤 정수값을 가지는 배열을 생성합니다.

```
배열 = np.random.randint(범위1, 범위2, shape)
```

In [46]:
a = np.random.randint(0, 10, shape)
a, a.shape

(array([[1, 3, 5],
        [1, 7, 2]]), (2, 3))

#### **3. `random.normal()`**

![ ]( https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Standard_deviation_diagram.svg/350px-Standard_deviation_diagram.svg.png)

정규분포 (normal distribution) 을 따르는 랜덤 값 배열을 생성합니다. 정규분포의 평균은 0, 표준편차는 1입니다.

```
배열 = np.random.normal(평균, 표준편차, shape)
```

In [67]:
a = np.random.normal(0, 1, shape)
a, a.shape

(array([[-0.88124461,  0.14695169, -0.08970962],
        [ 0.43345764, -1.38375052, -0.09417493]]), (2, 3))

#### **4. `random.rand()`**

균등분포 (unifrom distribution)을 따르는 랜덤한 수의 배열 생성합니다.

```
배열 = np.random.rand(shape)
```

In [64]:
a = np.random.rand(10,2)
a, a.shape

(array([[0.26064189, 0.06613026],
        [0.13680235, 0.84597517],
        [0.65505804, 0.41370946],
        [0.42426366, 0.92716355],
        [0.04001995, 0.58590725],
        [0.73279738, 0.03094837],
        [0.50527466, 0.99520567],
        [0.98078165, 0.709721  ],
        [0.93903671, 0.86839058],
        [0.51490675, 0.05379125]]), (10, 2))

#### **5. `random.randn()`**

표준 정규 분포(standard normal distribution)를 따르는 랜덤한 수의 배열을 생성합니다.

```
배열 = np.random.randn(shape)
```

In [66]:
a = np.random.randn(3,2)
a, a.shape

(array([[ 2.11628175, -0.67241822],
        [ 2.04489694, -0.66543574],
        [ 1.93043413,  0.95041824]]), (3, 2))

### **(5) 데이터 타입**

| 함수 | 설명 |
|--|--|
| `bool_` | 불리언(Boolean) 값. True, False 값을 지님|
| `int_` | 정수 (integer)|
| `intc` |  c 언어에서 사용되는 `int` 와 동일 |
| `intp` | 인덱싱에 사용되는 정수 |
| `int8` | 바이트(Byte)(-128 ~ 127)|
| `int16` | 정수 |
| `int32` | 정수|
| `int64` | 정수 |
| `uint8` | 부호없는 정수 (0~ 255) |
| `uint16` | 부호없는 정수  |
| `uint32` | 부호없는 정수  |
| `uint64` | 부호없는 정수 |
| `float16` | 반정밀 부동 소수점(Yalf precision float) |
| `float32` | 단정밀 부동 소수점(Single precision float)|
| `float64` | 배정밀 부동 소수점(Double precision float)|
| `float_` | =`float64` |
| `complex64` | 복소수, 두개의 32비트 부동 소수점으로 표현|
| `complex128` | 복소수, 두개의 64비트 부동 소수점으로 표현 |
| `complex_` | =`complex128` |





```
배열 = np.생성(dtype=타입)
```



In [76]:
a = np.random.random(shape)
print(a, a.shape)
a = np.array(a, dtype='float16')
print(a, a.shape)
a = np.array(a, dtype='float64')
print(a, a.shape)

[[0.82061176 0.42327873 0.18523209]
 [0.65223822 0.33413571 0.29684237]] (2, 3)
[[0.821  0.4233 0.1852]
 [0.6523 0.3342 0.2969]] (2, 3)
[[0.82080078 0.42333984 0.18518066]
 [0.65234375 0.33422852 0.296875  ]] (2, 3)


## 예제
---

####**예제 01**

아래 그림의 값과 shape를 가지는 데이터 배열을 생성하고 출력하세요. 그림에서 보이지 않는 값들은 0으로 정의하세요

![](https://ichi.pro/assets/images/max/724/1*X0Dg7QfSYtWhSAu-afi8-g.png)




* 1D array

* 2D array

* 3D array

####**예제 02**

**예제01** 에서 만든 1d 배열의 shape와 똑같은 shape를 가지는 배열을 만드세요, 단 모든 값은 1입니다. 


####**예제 03**

**예제01** 에서 만든 2d 배열의 shape와 똑같은 shape를 가지는 배열을 만들고 출력하세요, 단 모든 값은 0입니다. 


####**예제 04**

**예제01** 에서 만든 3d 배열의 shape와 똑같은 shape를 가지는 배열을 만들고 출력하세요, 단 모든 값은 10입니다.


####**예제 05**

1에서 100까지 홀수값만을 가지는 배열을 `np.arrange`를 이용해 만드세요


####**예제 06**

1에서 100까지 홀수값만을 가지는 배열을 `np.linspace`를 이용해 만드세요


####**예제 07**

shape가 (5,5)인 단위행렬(Identity matrix)를 생성하고 출력하세요


####**예제 08**

shape가 (1,5,5)인 배열을 생성하고 출력하세요. 단 배열은 균등분포를 따르는 랜덤값입니다.


####**예제 09**

shape가 (2,2,2)인 배열을 생성하고 출력하세요. 단 배열은 표준정규분포 를 따르는 랜덤값입니다.


####**예제 10**

**예제01** 에서 만든 배열들의 shape와 데이터 type을 확인하세요. 1d, 2d, 3d 배열의 타입을 각각 int64, float64, uint8로 변경한 배열을 생성하고 타입을 확인하세요