# 02. 넘파이: 배열 다루기
---
* 날짜:
* 이름:


Numpy(Numerical Python)는 고성능 과학 계산을 위한 파이썬 패키지로 강렬한 N차원의 배열(array)을 제공합니다. 이 배열은 범용적인 데이터 처리에 사용 가능한 다차원 컨테이너라 할 수 있으며 파이썬의 list와 비슷하지만 더 빠르고 효율적으로 메모리를 관리합니다. 배열에 대한 여러가지 연산 등 처리를 제공하며 데이터과학의 핵심이라 할 수 있습니다.

https://numpy.org/



```
import numpy as np
```



In [1]:
import numpy as np

## 개념정리
---



### **(1) 배열 조회**




<p align="center">
<img src="https://docs.sangyunlee.com/~/files/v0/b/gitbook-28427.appspot.com/o/assets%2F-LxaqUhwPNPE0iJCKfjJ%2F-MUgfOmYMQC2EJUN2rq_%2F-MUgttBGp-6BNnfXwC4R%2Fimage.png?alt=media&token=e3d4ca35-8fc8-473b-833a-f61ee70ab527" width=500>
</p>

|코드| 설명|
|--|--|
|`.ndim`| 차원의 개수|
|`.shape`| 모양|
|`.dtype`| 데이터타입|
|`.size`| element 개수|
|`.itemsize`| 표현 사이즈(byte)|
|`.nbytes`| size*itemsize|

In [ ]:
def arr_info(a):
  print("************************")
  print("* 차원의 개수: ", a.ndim)
  print("* 데이터 shape: ",a.shape)
  print("* 데이터 타입: ", a.dtype)
  print("* 데이터 size: ", a.size)


a1 = np.array([2,5,6,9])
a2 = np.array([[3,5,6],[7,8,9]])
a3 = np.zeros((4,3,2))

arr_info(a1)
arr_info(a2)
arr_info(a3)

************************
* 차원의 개수:  1
* 데이터 shape:  (4,)
* 데이터 타입:  int64
* 데이터 size:  4
************************
* 차원의 개수:  2
* 데이터 shape:  (2, 3)
* 데이터 타입:  int64
* 데이터 size:  6
************************
* 차원의 개수:  3
* 데이터 shape:  (4, 3, 2)
* 데이터 타입:  float64
* 데이터 size:  24


### **(2) 인덱싱과 슬라이싱**

<p align="center">
<img src="https://i.stack.imgur.com/Q3kpa.png width="300">
</p>



#### **1. 인덱싱**



```
# 1차원배열
a1[n] # n번째 값
# 다차원 배열
am[n1, n2, ..., nm] # 쉼표(,)로 각 차원 인덱싱 접근
```


In [ ]:
a = np.array([[1,2,3],  # (0,0) (0,1) (0,2)
              [4,5,6]]) # (1,0) (1,1) (1,2)
#     행 열
# 1: (0, 0)
# 4: (1, 0)

print( a[0,0], a[1, 0] )
print( a[(0, 1) , (0, 0)])

a = np.arange(36).reshape(6,6)
print(a)

# ar = [2, 14, 32]
# 0,2  2,2   -1,2
ar = a[ (0, 2, -1), 2 ]
print(ar)

# 1, 8, 15, 22, 29 ab
ab = a[ (0, 1,2,3,4), (1,2,3,4,5) ]
print(ab)




1 4
[1 4]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[ 2 14 32]
[ 1  8 15 22 29]


#### **2. 슬라이싱**

* default
  * start =0
  * stop = ndim
  * step =1

```
a[start:stop:step] 
```



In [ ]:
print(a)
print(a[(3,4,5), (0,0,0)], a[3:, 0])
print(a[(3,4,5), (2,2,2)], a[3:, 2])
print(a[(3,4,5), (5,5,5)], a[3:, 5])
print(a[3:, (0, 2, 5)])

# 1번
# [1 2]
# [7 8]   shape= (2,2)

print(a[0:2, 1:3])
print(a[:2, 1:3])
print(a[:2, (1,2)])

# 2번
# [15 16 17]
# [27 28 29]  shape=(2,3)
a[(2,4), 3:]

# 스텝추가

#a[ (2번째행, 4번째행) , 열시작:열끝 ]
a[(2,4), ::2]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[18 24 30] [18 24 30]
[20 26 32] [20 26 32]
[23 29 35] [23 29 35]
[[18 20 23]
 [24 26 29]
 [30 32 35]]
[[1 2]
 [7 8]]
[[1 2]
 [7 8]]
[[1 2]
 [7 8]]


array([[12, 14, 16],
       [24, 26, 28]])

####**3. 불리언 인덱싱(Boolean indexing)**

배열 각 요소의 선택 여부를 불리언(True or False)로 지정합니다. 그리고 나서 True 값인 인덱스의 값만 조회 합니다.



```
a = [10, 11, 12, 13, 14]
b = [True, False, True, False, True]
a[b]
```





In [ ]:
a = np.array([10, 11, 12, 13, 14])
b = np.array([True, False, True, False, True])
a[b]

a = np.arange(10).reshape(2,5)
b = np.array([[True,True,False,True,True],
              [True,True,True,True,True]])
print(a, a.shape)
print(a[b])

[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[0 1 3 4 5 6 7 8 9]


####**4. 팬시 인덱싱(Fancy indexing)**

배열 각 요소의 선택 여부를 인덱싱으로 지정합니다. 인덱싱의 shape 에 따라 배열 shape 변경이 가능합니다.


```
a = np.array([10, 11, 12, 13, 14])
b1 = [0,1,3,4]
print(a[b1])
b2 = np.array([[0,1],
               [3,4]])
print(a[b2])

```






In [ ]:
a = np.array([10, 11, 12, 13, 14])
# c =  [11, 12]
b = [ 1,  2 ]
a[b]
# c = [11, 13]
#     [13, 14]
b = np.array([[ 1, 3 ], 
              [ 3, 4 ]])
a[b]
# c = [ 12, 13, 14  ]
#     [ 10, 11, 11  ]
b = np.array([[ 2,3,4 ],
              [ 0,1,1 ]])
a[b]

array([[12, 13, 14],
       [10, 11, 11]])

```
print(a2)
row = np.array([0,1])
col = np.array([2,2])
print(a2[row, col])
print(a2[row, :])
print(a2[:, col])
print(a2[row, 1])
print(a2[1, col])
print(a2[row, 1:])
print(a2[1:, col])
```



### **(2) 배열 값 변경**




#### **1. 삽입: `insert()`**

배열의 특정 위치에 값을 삽입합니다. 배열 값을 추가할 axis를 지정해야 하며 만약  axis를 지정하지 않으면 1차원 배열로 변환합니다. 원본 배열은 변경없으며 새로운 배열을 반환합니다. 



```
배열2 = np.insert(배열1, 위치, 값)
```



In [10]:
a = np.arange(9).reshape(3,3)
print(a, a.shape)
np.insert(a, 5, 100)

[[0 1 2]
 [3 4 5]
 [6 7 8]] (3, 3)


array([  0,   1,   2,   3,   4, 100,   5,   6,   7,   8])

```
print(a2)
b2 = np.insert(a2, 1, 10, axis=0)
c2 = np.insert(a2, 1, 10, axis=1)
d2 = np.insert(a2, 1, 10)
print(b2)
print(c2)
print(d2)
```


In [12]:
print(a, a.shape)
b2 = np.insert(a, 1, 10, axis=0)
c2 = np.insert(a, 1, 10, axis=1)
d2 = np.insert(a, 1, 10)
print(b2, b2.shape)
print(c2, c2.shape)
print(d2, d2.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]] (3, 3)
[[ 0  1  2]
 [10 10 10]
 [ 3  4  5]
 [ 6  7  8]] (4, 3)
[[ 0 10  1  2]
 [ 3 10  4  5]
 [ 6 10  7  8]] (3, 4)
[ 0 10  1  2  3  4  5  6  7  8] (10,)


#### **2. 삭제: `delete()`**

 배열 값을 삭제할 axis를 지정해야 하며 만약  axis를 지정하지 않으면 1차원 배열로 변환합니다. 원본 배열은 변경없으며 새로운 배열을 반환합니다. 





```
배열2 = np.delete(배열1, 위치)
```





In [17]:
print(a, a.shape)
#c1 -> 2,3
c1=np.delete(a, 1, axis=0)
print(c1, c1.shape)
#c2 -> 3,2
c2=np.delete(a, 2, axis=1)
print(c2, c2.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]] (3, 3)
[[0 1 2]
 [6 7 8]] (2, 3)
[[0 1]
 [3 4]
 [6 7]] (3, 2)




```
print(a2)
b2 = np.delete(a2, 1, axis=0)
c2 = np.delete(a2, 1, axis=1)
d2 = np.delete(a2, 1)
print(b2)
print(c2)
print(d2)
```



In [18]:
print(a)
b2 = np.delete(a, 1, axis=0)
c2 = np.delete(a, 1, axis=1)
d2 = np.delete(a, 1)
print(b2)
print(c2)
print(d2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [6 7 8]]
[[0 2]
 [3 5]
 [6 8]]
[0 2 3 4 5 6 7 8]


#### **3. 수정: 인덱싱 이용**

배열의 인덱싱으로 특정값에 접근하고 값을 수정할 수 있습니다.



```
print(a1)
a1[1] = 111
print(a1)
a1[1:] = 222
print(a2)
```



In [20]:
a1 = np.arange(10)
print(a1, a1.shape)
print(a2, a2.shape)

print(a1)
a1[1] = 111
print(a1)
a1[1:] = 222
print(a1)

[0 1 2 3 4 5 6 7 8 9] (10,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[0 1 2 3 4 5 6 7 8 9]
[  0 111   2   3   4   5   6   7   8   9]
[  0 222 222 222 222 222 222 222 222 222]




```
print(a2)
a2[0,0] = 111
print(a2)
a2[0,:] = 222
```

In [24]:
a2 = np.arange(12).reshape(3,4)
print(a2)
a2[0,0] = 111
print(a2)
a2[0,:] = 222
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[111   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[[222 222 222 222]
 [  4   5   6   7]
 [  8   9  10  11]]


#### **4. 복사: `copy()`**


```
배열2 = 배열1.copy()
```






슬라이싱으로 배열을 복사하면 원본 배열이 변합니다.

```
print(a2)
print(a2[:1],a2[:1])
a2_sub = a2[:1, :1]
print(a2_sub)
a2_sub[:,1] = 100
print(a2_sub)
print(a2)
```


In [29]:
a2 = np.arange(9).reshape(3,3)
print("원본\n", a2)
a2_sub = a2[:2, :2]
print("sub 배열 (원본 슬라이싱)\n", a2_sub)
a2_sub[:,1] = 100
print("sub 배열 100으로 변경\n", a2_sub)
print("원본\n", a2)

원본
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
sub 배열 (원본 슬라이싱)
 [[0 1]
 [3 4]]
sub 배열 100으로 변경
 [[  0 100]
 [  3 100]]
원본
 [[  0 100   2]
 [  3 100   5]
 [  6   7   8]]


In [34]:
a = np.arange(16).reshape(4,4)
print(a, a.shape)

a = np.insert(a, 0, 0, axis=0)
print(a, a.shape)

a[0]=10
print(a, a.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] (4, 4)
[[ 0  0  0  0]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] (5, 4)
[[10 10 10 10]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] (5, 4)


`copy()`를 이용하여 원본 배열을 보존할 수 있습니다.

```
print(a2)
print(a2[:1],a2[:1])
a2_sub_copy = a2[:1, :1]
print(a2_sub_copy)
a2_sub_copy[:,1] = 100
print(a2_sub_copy)
print(a2)
```

In [40]:
a2 = np.arange(9).reshape(3,3)
print(a2)

b2 = a2.copy()
print(b2)

b2[0]=1
print(b2)
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 1 1]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 예제
---

####**예제 01**

아래 그림의 값과 shape를 가지는 데이터 배열을 생성하고 출력하세요. 3D array 그림에서 보이지 않는 값들은 가장 앞의 축과 동일하게 설정하세요. 생성한 배열의 정보를 조회하는 함수를 만들고 실행하세요

![](https://ichi.pro/assets/images/max/724/1*X0Dg7QfSYtWhSAu-afi8-g.png)




**01-1**

 1D array의 3을 인덱싱 하세요

**01-2**

2D array의 1을 모두 인덱싱 하세요

**01-3**

3D array의 3을 모두 인덱싱 하세요

**01-4**

2D array에 불리언 인덱싱을 이용하여 하여 새로운 배열 `[3,4,1]`을 만드세요

**01-5**

2D array에 펜시 인덱싱을 이용하여 하여 새로운 배열 `[[1,0],[3,4]]`을 만드세요

In [ ]:
d2  = np.array([[1,0,1], [3,4,1]])
d2 = np.array([1,0,1,3,4,1])

**01-6**

3D array에 불리언 인덱싱을 이용하여 하여 새로운 배열 `[7,9]` 혹은 `[9,7]`을 만드세요

**01-7**

3D array를 1차원 배열로 바꾼후 펜시 인덱싱을 이용하여 하여 새로운 배열 `[ [[5,9,3], [7,9,9]] , [[5,9,3], [7,9,9]] ]`을 만드세요

####**예제 02**

**예제 01** 의 2d array를 복사하세요



**02-1**

복사한 배열의 1번째 column 을 100으로 바꿉니다. `[ [1,100,1], [3, 100, 1]]`

**02-2**

0번째 row 을 -100으로 바꿉니다. `[ [-100,-100,-100], [3, 100, 1]]`

**02-3**

2번째 col을 삭제합니다.  `[ [-100,-100], [3, 100]]`

**02-4**

0과 1 사이에 1000을 추가합니다.  `[ [-100,1000,-100], [3, 1000,100]]`

####**예제 03**

아래 네 그림의 색칠된 부분을 슬라이싱 하여 새로운 배열을 만드세요 생성된 배열을 출력하고 shape를 확인하세요

![](https://github.com/yebiny/Lecture-EDA-basic/blob/main/imgs/02-np%EC%9D%B8%EB%8D%B1%EC%8B%B1.PNG?raw=true)


